<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Referencing the AppHost is what makes Projects.AppHost available below. -->
    <ProjectReference Include="..\..\src\AppHost\AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Aspire.Hosting" />
    <Using Include="Aspire.Hosting.Testing" />
  </ItemGroup>

</Project>
